[WIP] Fix missing check in sync triggers
ansible/django-ansible-base pull request #386
Opened 2024-05-13 14:31 UTC by cutwater

Check if `pk_set` is a True-like (e.g. non-empty set) object.

The `pk_set` parameter may be `None` in cases when user teams list is cleared (e.g. calling `user.teams.clear()`).

This code will fail with the following exception:

```
TypeError: 'NoneType' object is not iterable
```

due to attempt to iterate over `None` value.

2024-05-14 17:15 UTC, AlanCoding requested changes
`user.teams.clear()` is expected to remove that user from the corresponding team's member role. This change would do nothing in that event, causing the relationship's membership to differ from the role's membership.

2024-05-15 10:56 UTC, cutwater commented
@AlanCoding I added tests that demonstrate this behavior.

Unless it's fixed the `user.teams.clear()` call will raise an exception:

```
rando = <User: rando>

    @pytest.mark.django_db
    def test_user_teams_clear(rando):
>       rando.teams.clear()

test_app/tests/rbac/features/test_role_tracking.py:78: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.tox/py311/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py:1176: in clear
    signals.m2m_changed.send(
.tox/py311/lib/python3.11/site-packages/django/dispatch/dispatcher.py:176: in send
    return [
.tox/py311/lib/python3.11/site-packages/django/dispatch/dispatcher.py:177: in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <ansible_base.rbac.triggers.TrackedRelationship object at 0x7fc28b07a110>, instance = <User: rando>, action = 'pre_clear', model = <class 'test_app.models.Team'>, pk_set = None, reverse = True, kwargs = {'sender': <class 'test_app.models.Team_users'>, 'signal': <django.db.models.signals.ModelSignal object at 0x7fc28da59790>, 'using': 'default'}
memo = <typeguard.TypeCheckMemo object at 0x7fc28a46ddc0>

    def sync_user_to_role(self, instance: Model, action: str, model: type, pk_set: Optional[set[int]], reverse: bool, **kwargs):
        if not reverse:
            self._sync_actor_to_role(permission_registry.user_model, instance, action, pk_set)
        else:
>           for pk in pk_set:
E           TypeError: 'NoneType' object is not iterable
```

In addition to that the `pg_set` parameter in function is annotated as `Optional`, which means it's nullable. So iterating over it without additional checks is a mistake.

2024-05-15 11:02 UTC, cutwater commented
I analyzed the code a bit deeper and while my root cause analysis is accurate, it seems that the fix is not sufficient. The code doesn't handle `pre_clear` event correctly, which is what should be really fixed.

2024-05-16 18:33 UTC, cutwater commented
This PR is obsolete, since the TrackedRelationship feature is about to be deprecated and will be removed in future.

2024-05-16 18:33 UTC, closed without merging