Save simple default settings in a separate module
ansible/django-ansible-base pull request #526
Opened 2024-07-26 17:33 UTC by AlanCoding

Working through https://github.com/ansible/galaxy_ng/pull/2202 with @jctanner I discovered it wasn't loading the settings. In short, I don't think we can rely on accurately having `INSTALLED_APPS` populated at the time we needed to load the defaults.

But we shouldn't need this. If an app wants to bypass our recommended system (which it is already doing), then it should have a constant data structure to import.

I wanted to do this with dictionaries too, but it seems we have special cases for each entry, which... I can't tough. So this is unfortunately incomplete.

2024-07-26 18:15 UTC, rochacbruno approved these changes
LGTM will make it easier to load the settings.

2024-07-26 22:51 UTC, relrod requested changes
I'm not rejecting for any technical reason, but I just want to better understand the problem before this goes in.

i.e. What exactly is the problem with INSTALLED_APPS?

2024-07-29 13:17 UTC, AlanCoding commented on ansible_base/lib/dynamic_config/dynamic_settings.py
> +    locals()[key] = value
FWIW, it is not suggested to do this

https://docs.python.org/3/library/functions.html#locals

> Note The contents of this dictionary should not be modified; changes may not affect the values of local and free variables used by the interpreter.

2024-07-29 18:56 UTC, AlanCoding commented
> i.e. What exactly is the problem with INSTALLED_APPS?

I'll link you the thing that ultimately needs to be fixed here

https://github.com/ansible/galaxy_ng/blob/b26816eaf9c1e34f4033835e09125013a5d182d3/galaxy_ng/app/dynaconf_hooks.py#L732

There's a method that needs to return a dictionary of the settings from DAB. It's probably already obvious to you that this poses an issue for any settings that have to get fine-grained merged. But I don't think galaxy_ng is using any part of DAB that requires that at this moment, and I'm not sure how it would work if we did have that situation.

But you mention `INSTALLED_APPS`. This would have to be included in local variables to pass the value, and that's just not the right way to do thing. I don't even really know if `split_settings` works within a function's variable scope, or if it might mess up something else.

2024-07-30 18:03 UTC, AlanCoding commented
For an immediate solution I prefer the other approach. We could do a version of this later (to define truly static settings), but it is not necessary.

2024-07-30 18:03 UTC, closed without merging