Support modifying groups claim for social auth
ansible/django-ansible-base pull request #640
Opened 2024-11-07 22:44 UTC by markafarrell

By default social auth hard codes the groups claim to `Group`.

In general IDPs use `groups` for returning the user group membership.

This PR support setting the groups claim field

2024-11-13 21:15 UTC, bhavenst requested changes
Thanks for the PR!

2024-11-13 21:15 UTC, bhavenst commented on ansible_base/authentication/authenticator_plugins/oidc.py
> +    GROUPS_CLAIM = CharField(
Could you add this to keycloak.py backend as well?  It's also using oidc and could benefit from the same flexibility.

2024-11-13 21:15 UTC, bhavenst commented on ansible_base/authentication/authenticator_plugins/oidc.py
> +        help_text=_("The JSON key used to extract the user's groups from the ID token or userinfo endpoint."),
Help text is copy/paste from USERNAME_KEY, update for GROUPS_CLAIM

2024-11-13 21:52 UTC, markafarrell commented on ansible_base/authentication/authenticator_plugins/oidc.py
> +        help_text=_("The JSON key used to extract the user's groups from the ID token or userinfo endpoint."),
It's actually different `The JSON key used to extract the user's groups` vs `The JSON key used to extract the user's username`

2024-11-13 21:53 UTC, markafarrell commented on ansible_base/authentication/authenticator_plugins/oidc.py
> +    GROUPS_CLAIM = CharField(
@bhavenst I would prefer not to. I don't have keycloak setup to allow me to test that the change doesn't break anything and actually works.

2024-11-13 21:59 UTC, bhavenst commented on ansible_base/authentication/authenticator_plugins/oidc.py
> +        help_text=_("The JSON key used to extract the user's groups from the ID token or userinfo endpoint."),
Ah, missed the difference. :)  Thanks

2024-11-13 21:59 UTC, bhavenst commented on ansible_base/authentication/authenticator_plugins/oidc.py
> +    GROUPS_CLAIM = CharField(
OK, fair enough. I can add one myself.  I did actually test it already and it worked the same.

2024-11-13 21:59 UTC, bhavenst approved these changes

2024-11-18 10:35 UTC, relrod commented
@markafarrell thanks for this!

2024-11-18 10:36 UTC, merged